// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoLte0demU50QQ4XkkfWxNKrBSu5weyE',
    appId: '1:118014846722:web:996771d37226690b98441b',
    messagingSenderId: '118014846722',
    projectId: 'ai-outfit-recommender-ap-d7a10',
    authDomain: 'ai-outfit-recommender-ap-d7a10.firebaseapp.com',
    storageBucket: 'ai-outfit-recommender-ap-d7a10.firebasestorage.app',
    measurementId: 'G-2RGSZM0JVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tn1hpeUBBj00VE2z28Kyb0imK271m0Q',
    appId: '1:118014846722:android:950ce1c0412d170898441b',
    messagingSenderId: '118014846722',
    projectId: 'ai-outfit-recommender-ap-d7a10',
    storageBucket: 'ai-outfit-recommender-ap-d7a10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7We6YsN-oEAoLshT-CQqi3rjaTGxdQc',
    appId: '1:118014846722:ios:cc9a9d28ab02efbf98441b',
    messagingSenderId: '118014846722',
    projectId: 'ai-outfit-recommender-ap-d7a10',
    storageBucket: 'ai-outfit-recommender-ap-d7a10.firebasestorage.app',
    iosBundleId: 'com.example.aiOutfitRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7We6YsN-oEAoLshT-CQqi3rjaTGxdQc',
    appId: '1:118014846722:ios:cc9a9d28ab02efbf98441b',
    messagingSenderId: '118014846722',
    projectId: 'ai-outfit-recommender-ap-d7a10',
    storageBucket: 'ai-outfit-recommender-ap-d7a10.firebasestorage.app',
    iosBundleId: 'com.example.aiOutfitRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcoLte0demU50QQ4XkkfWxNKrBSu5weyE',
    appId: '1:118014846722:web:ca26752a77ba707598441b',
    messagingSenderId: '118014846722',
    projectId: 'ai-outfit-recommender-ap-d7a10',
    authDomain: 'ai-outfit-recommender-ap-d7a10.firebaseapp.com',
    storageBucket: 'ai-outfit-recommender-ap-d7a10.firebasestorage.app',
    measurementId: 'G-7ESFD2XD08',
  );
}
